### ISSUE TITLE
Integration in `events`?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [skerbis/yform_calhelper#1]
Hi! Wäre es nicht sinnvoll, das standardmäßig auf das `events` Add-on zu münzen oder zu integrieren? 

Da gibt's bereits auch schon Funktionen dazu, z.B. ics oder Methoden zum Abruf / Sortieren von Kalendereinträgen sowie Kompatibilität zu fullcalendar.

Was ist die Motivation für ein eigenes Addon?

**Comment by skerbis** [comment]
habe noch Probleme mit Speicherüberläufen , … 
Grundsätzlich soll es eigentlich kein Addon im eigentlichen Sinne sein. Es soll nur eine Hilfclass für beliebige Kalender-Tabellen sein. ICS ist hier schon vorgesehen  als Export. Für FullCalendar habe ich hier eine kleine Class integriert.

**Comment by AWqxKAWERbXo** [comment]
Ok gut zu wissen
